/**
 * Auto-generated Supabase database types.
 * Regenerate after every migration:
 *   pnpm supabase gen types typescript --local > src/lib/supabase/types.ts
 *
 * DO NOT edit this file manually.
 */

// Placeholder until first `supabase gen types` run.
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export type Database = {};
