-- T03 CI proof of P09M1, plus T08-DB proof of P09M2.
-- One result set: name, expected, actual, pass.
-- CASE_COUNT is 59 pg_temp.rec calls. all_pass checks that count.
-- Do not change an expected value to match a wrong actual.
-- P09M2 cases cite S1 (human, 2026-10-04), the live enum labels
-- (SELECT 2026-10-04), and the writer named on each case.
--
-- Sources on each case: pack PHASE_09_V2_SURFACES.md §5, F-P1, F-P2,
-- plan §8.2.5, R-S10, REG-65, AC-CAT-2, the category-cap function.
-- CI admin_settings values are labelled CI TEST VALUE. They are not the
-- staging strings and they are not food-v1.

SET TIME ZONE 'UTC';

BEGIN;

CREATE TEMP TABLE p09_results (
  ord integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  expected text,
  actual text,
  pass boolean NOT NULL
) ON COMMIT DROP;

CREATE FUNCTION pg_temp.rec(p_name text, p_expected text, p_actual text)
RETURNS void
LANGUAGE plpgsql
AS $rec$
BEGIN
  INSERT INTO p09_results (name, expected, actual, pass)
  VALUES (p_name, p_expected, p_actual, p_expected IS NOT DISTINCT FROM p_actual);
END;
$rec$;

CREATE FUNCTION pg_temp.try_exec(p_sql text)
RETURNS text
LANGUAGE plpgsql
AS $try$
BEGIN
  EXECUTE p_sql;
  RETURN 'ok';
EXCEPTION WHEN OTHERS THEN
  RETURN SQLERRM;
END;
$try$;

CREATE FUNCTION pg_temp.exec_as(p_uid uuid, p_role text, p_sql text)
RETURNS text
LANGUAGE plpgsql
AS $exec$
DECLARE
  v_msg text;
BEGIN
  IF p_uid IS NULL THEN
    PERFORM set_config('request.jwt.claim.sub', '', true);
    PERFORM set_config('request.jwt.claims', '{}', true);
  ELSE
    PERFORM set_config('request.jwt.claim.sub', p_uid::text, true);
    PERFORM set_config(
      'request.jwt.claims',
      json_build_object('sub', p_uid, 'role', p_role)::text,
      true
    );
  END IF;
  EXECUTE format('SET ROLE %I', p_role);
  BEGIN
    EXECUTE p_sql;
    v_msg := 'ok';
  EXCEPTION WHEN OTHERS THEN
    v_msg := SQLERRM;
  END;
  EXECUTE 'RESET ROLE';
  PERFORM set_config('request.jwt.claim.sub', '', true);
  PERFORM set_config('request.jwt.claims', '{}', true);
  RETURN v_msg;
END;
$exec$;

DO $cases$
DECLARE
  v_seller uuid := 'b1000000-0000-4000-8000-000000000001';
  v_cap_seller uuid := 'b1000000-0000-4000-8000-000000000002';
  v_stamp_seller uuid := 'b1000000-0000-4000-8000-000000000003';
  v_submit uuid := 'b1000000-0000-4000-8000-000000000004';
  v_resubmit uuid := 'b1000000-0000-4000-8000-000000000005';
  v_admin uuid := 'b1000000-0000-4000-8000-000000000006';
  v_store uuid := 'b2000000-0000-4000-8000-000000000001';
  v_cap_store uuid := 'b2000000-0000-4000-8000-000000000002';
  v_stamp_store uuid := 'b2000000-0000-4000-8000-000000000003';
  v_resubmit_store uuid := 'b2000000-0000-4000-8000-000000000004';
  v_listing uuid := 'b3000000-0000-4000-8000-000000000001';
  v_arts uuid;
  v_food uuid;
  v_other uuid;
  v_stamp_a uuid;
  v_stamp_b uuid;
  v_stamp_c uuid;
  v_cap_ids uuid[];
  v_cap_id uuid;
  v_msg text;
  v_n integer;
  v_reason text;
  v_opts text;
  v_gate uuid := 'b1000000-0000-4000-8000-000000000007';
  v_reset uuid := 'b1000000-0000-4000-8000-000000000008';
  v_extra uuid := 'b1000000-0000-4000-8000-000000000009';
  v_gate_store uuid := 'b2000000-0000-4000-8000-000000000005';
  v_reset_store uuid := 'b2000000-0000-4000-8000-000000000006';
BEGIN
  INSERT INTO betk.users (id, role, status, phone_number) VALUES
    (v_seller, 'seller', 'active', '01090000001'),
    (v_cap_seller, 'seller', 'active', '01090000002'),
    (v_stamp_seller, 'seller', 'active', '01090000003'),
    (v_submit, 'seller', 'active', '01090000004'),
    (v_resubmit, 'seller', 'active', '01090000005'),
    (v_admin, 'admin', 'active', '01090000006');

  INSERT INTO betk.seller_profiles (id, status) VALUES
    (v_seller, 'active'),
    (v_cap_seller, 'active'),
    (v_stamp_seller, 'active');

  INSERT INTO betk.seller_profiles (id, status, rejected_reason)
  VALUES (v_resubmit, 'pending', 'ci');

  INSERT INTO betk.stores (
    id, seller_id, name_ar, slug, governorate, city, category_primary, status
  ) VALUES
    (v_store, v_seller, 'CI A', 'ci-p09-a', 'Cairo', 'Cairo', 'ci', 'active'),
    (v_cap_store, v_cap_seller, 'CI B', 'ci-p09-b', 'Cairo', 'Cairo', 'ci', 'active'),
    (v_stamp_store, v_stamp_seller, 'CI C', 'ci-p09-c', 'Cairo', 'Cairo', 'ci', 'active'),
    (v_resubmit_store, v_resubmit, 'CI D', 'ci-p09-d', 'Cairo', 'Cairo', 'ci', 'pending');

  INSERT INTO betk.seller_documents (seller_id, document_type, storage_path)
  VALUES
    (v_resubmit, 'national_id_front', 'ci/r-front'),
    (v_resubmit, 'national_id_back', 'ci/r-back');

  SELECT id INTO v_arts FROM betk.categories WHERE slug = 'arts-crafts';
  SELECT id INTO v_food FROM betk.categories WHERE slug = 'food-herbs';
  SELECT id INTO v_other FROM betk.categories WHERE slug = 'jewelry-accessories';
  SELECT id INTO v_stamp_a FROM betk.categories WHERE slug = 'jewelry-handmade';
  SELECT id INTO v_stamp_b FROM betk.categories WHERE slug = 'jewelry-gold-silver';
  SELECT id INTO v_stamp_c FROM betk.categories WHERE slug = 'jewelry-bags';
  SELECT array_agg(id ORDER BY slug) INTO v_cap_ids
  FROM betk.categories
  WHERE slug IN ('arts-paintings', 'arts-pottery', 'arts-sewing', 'arts-crochet');
  IF v_arts IS NULL OR v_food IS NULL OR v_other IS NULL
     OR v_stamp_a IS NULL OR v_stamp_b IS NULL OR v_stamp_c IS NULL
     OR v_cap_ids IS NULL OR cardinality(v_cap_ids) <> 4 THEN
    RAISE EXCEPTION 'BETK_P09_FIXTURE_CATEGORY';
  END IF;

  -- CI TEST VALUE. Numeric pins, not the staging band 1 / 1000000.
  -- prep_cap_days '3' matches the M3 default and is labelled here.
  UPDATE betk.admin_settings SET value = '3' WHERE key = 'prep_cap_days';
  UPDATE betk.admin_settings SET value = '10' WHERE key = 'price_band_min_egp';
  UPDATE betk.admin_settings SET value = '100' WHERE key = 'price_band_max_egp';

  INSERT INTO betk.store_categories (store_id, category_id)
  VALUES (v_store, v_arts);
  UPDATE betk.store_categories
  SET approved_at = timestamptz '2026-01-15 00:00:00+00'
  WHERE store_id = v_store AND category_id = v_arts;

  -- AC-CAT-1. Pack §5 (b). Active service.
  v_msg := pg_temp.try_exec(format(
    'INSERT INTO betk.listings (
       store_id, category_id, title_ar, type, price_type, price, stock_qty,
       status, weight_g, length_mm, width_mm, height_mm, prep_days
     ) VALUES (
       %L, %L, %L, %L::betk.listing_type, %L::betk.price_type, 50, 5,
       %L::betk.listing_status, 1, 1, 1, 1, 1
     )',
    v_store, v_arts, 'CI service', 'service', 'fixed', 'active'
  ));
  PERFORM pg_temp.rec('publish_service', 'BETK_LISTING_TYPE', v_msg);

  -- AC-CAT-5 / AC-CAT-6. Non-fixed price.
  v_msg := pg_temp.try_exec(format(
    'INSERT INTO betk.listings (
       store_id, category_id, title_ar, type, price_type, price, stock_qty,
       status, weight_g, length_mm, width_mm, height_mm, prep_days
     ) VALUES (
       %L, %L, %L, %L::betk.listing_type, %L::betk.price_type, 50, 5,
       %L::betk.listing_status, 1, 1, 1, 1, 1
     )',
    v_store, v_arts, 'CI hour', 'product', 'per_hour', 'active'
  ));
  PERFORM pg_temp.rec('publish_price_type', 'BETK_PRICE_TYPE', v_msg);

  -- R-L22. prep_days over the cap. Cap is the CI TEST VALUE 3.
  v_msg := pg_temp.try_exec(format(
    'INSERT INTO betk.listings (
       store_id, category_id, title_ar, type, price_type, price, stock_qty,
       status, weight_g, length_mm, width_mm, height_mm, prep_days
     ) VALUES (
       %L, %L, %L, %L::betk.listing_type, %L::betk.price_type, 50, 5,
       %L::betk.listing_status, 1, 1, 1, 1, 4
     )',
    v_store, v_arts, 'CI prep', 'product', 'fixed', 'active'
  ));
  PERFORM pg_temp.rec('publish_prep_cap', 'BETK_PREP_CAP', v_msg);

  -- AC-CAT-3. Price outside the CI TEST VALUE band 10..100.
  v_msg := pg_temp.try_exec(format(
    'INSERT INTO betk.listings (
       store_id, category_id, title_ar, type, price_type, price, stock_qty,
       status, weight_g, length_mm, width_mm, height_mm, prep_days
     ) VALUES (
       %L, %L, %L, %L::betk.listing_type, %L::betk.price_type, 101, 5,
       %L::betk.listing_status, 1, 1, 1, 1, 1
     )',
    v_store, v_arts, 'CI band', 'product', 'fixed', 'active'
  ));
  PERFORM pg_temp.rec('publish_price_band', 'BETK_PRICE_BAND', v_msg);

  -- Plan §8.2.5. Empty band fails closed. The empty text is the CI TEST VALUE
  -- for this case. It is not the staging band.
  UPDATE betk.admin_settings SET value = '' WHERE key = 'price_band_min_egp';
  UPDATE betk.admin_settings SET value = '' WHERE key = 'price_band_max_egp';
  v_msg := pg_temp.try_exec(format(
    'INSERT INTO betk.listings (
       store_id, category_id, title_ar, type, price_type, price, stock_qty,
       status, weight_g, length_mm, width_mm, height_mm, prep_days
     ) VALUES (
       %L, %L, %L, %L::betk.listing_type, %L::betk.price_type, 50, 5,
       %L::betk.listing_status, 1, 1, 1, 1, 1
     )',
    v_store, v_arts, 'CI empty band', 'product', 'fixed', 'active'
  ));
  PERFORM pg_temp.rec('publish_band_unconfigured', 'BETK_PRICE_BAND_UNCONFIGURED', v_msg);
  UPDATE betk.admin_settings SET value = '10' WHERE key = 'price_band_min_egp';
  UPDATE betk.admin_settings SET value = '100' WHERE key = 'price_band_max_egp';

  -- PRD AC-CAT-4. Category with no approved store_categories row.
  v_msg := pg_temp.try_exec(format(
    'INSERT INTO betk.listings (
       store_id, category_id, title_ar, type, price_type, price, stock_qty,
       status, weight_g, length_mm, width_mm, height_mm, prep_days
     ) VALUES (
       %L, %L, %L, %L::betk.listing_type, %L::betk.price_type, 50, 5,
       %L::betk.listing_status, 1, 1, 1, 1, 1
     )',
    v_store, v_other, 'CI unapproved', 'product', 'fixed', 'active'
  ));
  PERFORM pg_temp.rec('publish_category_unapproved', 'BETK_CATEGORY_NOT_APPROVED', v_msg);

  -- Approved category, and the AC-CAT-2 success half (all four dimensions).
  v_msg := pg_temp.try_exec(format(
    'INSERT INTO betk.listings (
       id, store_id, category_id, title_ar, type, price_type, price, stock_qty,
       status, weight_g, length_mm, width_mm, height_mm, prep_days
     ) VALUES (
       %L, %L, %L, %L, %L::betk.listing_type, %L::betk.price_type, 50, 5,
       %L::betk.listing_status, 1, 1, 1, 1, 1
     )',
    v_listing, v_store, v_arts, 'CI ok', 'product', 'fixed', 'active'
  ));
  PERFORM pg_temp.rec('publish_category_approved', 'ok', v_msg);

  -- AC-CAT-2. Pack §5 (a). Missing weight. The other gates would pass.
  v_msg := pg_temp.try_exec(format(
    'INSERT INTO betk.listings (
       store_id, category_id, title_ar, type, price_type, price, stock_qty,
       status, weight_g, length_mm, width_mm, height_mm, prep_days
     ) VALUES (
       %L, %L, %L, %L::betk.listing_type, %L::betk.price_type, 50, 5,
       %L::betk.listing_status, NULL, 1, 1, 1, 1
     )',
    v_store, v_arts, 'CI ship', 'product', 'fixed', 'active'
  ));
  PERFORM pg_temp.rec(
    'shipping_missing',
    'new row for relation "listings" violates check constraint "chk_active_listing_shipping"',
    v_msg
  );

  INSERT INTO betk.store_categories (store_id, category_id)
  VALUES (v_store, v_food);
  UPDATE betk.store_categories
  SET approved_at = timestamptz '2026-01-15 00:00:00+00'
  WHERE store_id = v_store AND category_id = v_food;

  -- Plan §8.2.5. Empty food_requirements fails closed. Migration default is
  -- empty text. The CI label for a configured value is set after this case.
  v_msg := pg_temp.try_exec(format(
    'INSERT INTO betk.listings (
       store_id, category_id, title_ar, type, price_type, price, stock_qty,
       status, weight_g, length_mm, width_mm, height_mm, prep_days
     ) VALUES (
       %L, %L, %L, %L::betk.listing_type, %L::betk.price_type, 50, 5,
       %L::betk.listing_status, 1, 1, 1, 1, 1
     )',
    v_store, v_food, 'CI food empty', 'product', 'fixed', 'active'
  ));
  PERFORM pg_temp.rec('food_label_empty', 'BETK_FOOD_REQUIREMENTS_UNCONFIGURED', v_msg);

  -- CI TEST VALUE. Not food-v1.
  UPDATE betk.admin_settings SET value = 'CI TEST VALUE' WHERE key = 'food_requirements';

  INSERT INTO betk.seller_documents (seller_id, document_type, storage_path, review_status)
  VALUES
    (v_seller, 'food_packaging', 'ci/pack', 'pending'),
    (v_seller, 'food_label', 'ci/label', 'pending'),
    (v_seller, 'food_expiry', 'ci/expiry', 'pending'),
    (v_seller, 'food_social_url', 'ci/social', 'pending');

  -- R-S10, F-P2. Approved food category, four docs still pending.
  v_msg := pg_temp.try_exec(format(
    'INSERT INTO betk.listings (
       store_id, category_id, title_ar, type, price_type, price, stock_qty,
       status, weight_g, length_mm, width_mm, height_mm, prep_days
     ) VALUES (
       %L, %L, %L, %L::betk.listing_type, %L::betk.price_type, 50, 5,
       %L::betk.listing_status, 1, 1, 1, 1, 1
     )',
    v_store, v_food, 'CI food pending', 'product', 'fixed', 'active'
  ));
  PERFORM pg_temp.rec('food_docs_pending', 'BETK_FOOD_APPROVAL_REQUIRED', v_msg);

  UPDATE betk.seller_documents
  SET review_status = 'approved'
  WHERE seller_id = v_seller
    AND document_type IN (
      'food_packaging', 'food_label', 'food_expiry', 'food_social_url'
    );

  -- R-S10, F-P2. All four approved. Descendant slug food-herbs.
  v_msg := pg_temp.try_exec(format(
    'INSERT INTO betk.listings (
       store_id, category_id, title_ar, type, price_type, price, stock_qty,
       status, weight_g, length_mm, width_mm, height_mm, prep_days
     ) VALUES (
       %L, %L, %L, %L::betk.listing_type, %L::betk.price_type, 50, 5,
       %L::betk.listing_status, 1, 1, 1, 1, 1
     )',
    v_store, v_food, 'CI food ok', 'product', 'fixed', 'active'
  ));
  PERFORM pg_temp.rec('food_docs_approved', 'ok', v_msg);

  -- F-P1. Revoke the category approval on the active listing, then the
  -- transitions that must stay unchecked, then the ones that publish again.
  UPDATE betk.store_categories
  SET approved_at = NULL
  WHERE store_id = v_store AND category_id = v_arts;

  v_msg := pg_temp.try_exec(format(
    'UPDATE betk.listings SET stock_qty = 6 WHERE id = %L',
    v_listing
  ));
  IF v_msg = 'ok' THEN
    SELECT stock_qty::text INTO v_opts FROM betk.listings WHERE id = v_listing;
    IF v_opts IS DISTINCT FROM '6' THEN
      v_msg := 'stock=' || coalesce(v_opts, 'null');
    END IF;
  END IF;
  PERFORM pg_temp.rec('fp1_stock_only', 'ok', v_msg);

  v_msg := pg_temp.try_exec(format(
    'UPDATE betk.listings SET status = %L::betk.listing_status WHERE id = %L',
    'sold_out', v_listing
  ));
  IF v_msg = 'ok' THEN
    v_msg := pg_temp.try_exec(format(
      'UPDATE betk.listings SET status = %L::betk.listing_status WHERE id = %L',
      'active', v_listing
    ));
  END IF;
  IF v_msg = 'ok' THEN
    SELECT status::text INTO v_opts FROM betk.listings WHERE id = v_listing;
    IF v_opts IS DISTINCT FROM 'active' THEN
      v_msg := 'status=' || coalesce(v_opts, 'null');
    END IF;
  END IF;
  PERFORM pg_temp.rec('fp1_sold_out_restore', 'ok', v_msg);

  v_msg := pg_temp.try_exec(format(
    'UPDATE betk.listings SET price = 60 WHERE id = %L',
    v_listing
  ));
  PERFORM pg_temp.rec('fp1_price_change', 'BETK_CATEGORY_NOT_APPROVED', v_msg);

  v_msg := pg_temp.try_exec(format(
    'UPDATE betk.listings SET status = %L::betk.listing_status WHERE id = %L',
    'paused', v_listing
  ));
  IF v_msg <> 'ok' THEN
    v_msg := 'pause:' || v_msg;
  ELSE
    v_msg := pg_temp.try_exec(format(
      'UPDATE betk.listings SET status = %L::betk.listing_status WHERE id = %L',
      'active', v_listing
    ));
  END IF;
  PERFORM pg_temp.rec('fp1_paused_to_active', 'BETK_CATEGORY_NOT_APPROVED', v_msg);

  -- Pack §5. Non-admin INSERT cannot keep approved_at. Service role is
  -- auth.uid() null, which is not is_admin().
  v_msg := pg_temp.exec_as(
    v_stamp_seller,
    'authenticated',
    format(
      'INSERT INTO betk.store_categories (store_id, category_id, approved_at)
       VALUES (%L, %L, %L::timestamptz)',
      v_stamp_store, v_stamp_a, '2026-02-01 00:00:00+00'
    )
  );
  IF v_msg <> 'ok' THEN
    v_opts := v_msg;
  ELSE
    SELECT CASE WHEN approved_at IS NULL THEN 'null' ELSE 'kept' END
    INTO v_opts
    FROM betk.store_categories
    WHERE store_id = v_stamp_store AND category_id = v_stamp_a;
    v_opts := coalesce(v_opts, 'norow');
  END IF;
  PERFORM pg_temp.rec('stamp_seller', 'null', v_opts);

  v_msg := pg_temp.exec_as(
    v_admin,
    'authenticated',
    format(
      'INSERT INTO betk.store_categories (store_id, category_id, approved_at)
       VALUES (%L, %L, %L::timestamptz)',
      v_stamp_store, v_stamp_b, '2026-02-01 00:00:00+00'
    )
  );
  IF v_msg <> 'ok' THEN
    v_opts := v_msg;
  ELSE
    SELECT CASE
      WHEN approved_at = timestamptz '2026-02-01 00:00:00+00' THEN 'kept'
      ELSE 'null'
    END
    INTO v_opts
    FROM betk.store_categories
    WHERE store_id = v_stamp_store AND category_id = v_stamp_b;
    v_opts := coalesce(v_opts, 'norow');
  END IF;
  PERFORM pg_temp.rec('stamp_admin', 'kept', v_opts);

  v_msg := pg_temp.exec_as(
    NULL,
    'service_role',
    format(
      'INSERT INTO betk.store_categories (store_id, category_id, approved_at)
       VALUES (%L, %L, %L::timestamptz)',
      v_stamp_store, v_stamp_c, '2026-02-01 00:00:00+00'
    )
  );
  IF v_msg <> 'ok' THEN
    v_opts := v_msg;
  ELSE
    SELECT CASE WHEN approved_at IS NULL THEN 'null' ELSE 'kept' END
    INTO v_opts
    FROM betk.store_categories
    WHERE store_id = v_stamp_store AND category_id = v_stamp_c;
    v_opts := coalesce(v_opts, 'norow');
  END IF;
  PERFORM pg_temp.rec('stamp_service', 'null', v_opts);

  -- Pack §5 (a). seller_category_limit is the M3 default 3. Fourth insert.
  FOREACH v_cap_id IN ARRAY v_cap_ids LOOP
    v_n := coalesce(v_n, 0) + 1;
    IF v_n < 4 THEN
      INSERT INTO betk.store_categories (store_id, category_id)
      VALUES (v_cap_store, v_cap_id);
    ELSE
      v_msg := pg_temp.try_exec(format(
        'INSERT INTO betk.store_categories (store_id, category_id) VALUES (%L, %L)',
        v_cap_store, v_cap_id
      ));
    END IF;
  END LOOP;
  PERFORM pg_temp.rec('category_cap', 'BETK_STORE_CATEGORY_CAP', v_msg);

  -- AC-AGR-3 and plan §8.2.5. The version key is still the migration empty
  -- text. That empty text is the CI TEST VALUE for the unconfigured case.
  -- It is not STAGING-DRAFT-1.
  v_msg := pg_temp.exec_as(
    v_submit,
    'authenticated',
    $sql$
      SELECT betk.submit_seller_application(
        'CI Submit', 'CI Submit', NULL, 'ci-p09-submit',
        'ci', NULL, 'Cairo', 'Cairo',
        '{}'::jsonb, '{"delivery_fee_egp":15}'::jsonb,
        NULL, NULL, 'ci/front', 'ci/back'
      )
    $sql$
  );
  SELECT count(*)::integer INTO v_n FROM betk.stores WHERE seller_id = v_submit;
  IF v_n <> 0 THEN
    v_msg := v_msg || '|rows';
  END IF;
  PERFORM pg_temp.rec('submit_version_unconfigured', 'BETK_AGREEMENT_VERSION_UNCONFIGURED', v_msg);

  v_msg := pg_temp.exec_as(
    v_resubmit,
    'authenticated',
    $sql$SELECT betk.resubmit_seller_application('ci/front2', 'ci/back2')$sql$
  );
  SELECT rejected_reason INTO v_reason
  FROM betk.seller_profiles WHERE id = v_resubmit;
  IF v_reason IS DISTINCT FROM 'ci' THEN
    v_msg := v_msg || '|wrote';
  END IF;
  PERFORM pg_temp.rec('resubmit_version_unconfigured', 'BETK_AGREEMENT_VERSION_UNCONFIGURED', v_msg);

  -- CI TEST VALUE. Not STAGING-DRAFT-1.
  UPDATE betk.admin_settings
  SET value = 'CI TEST VALUE'
  WHERE key = 'agreement_seller_agreement_version';

  v_msg := pg_temp.exec_as(
    v_submit,
    'authenticated',
    $sql$
      SELECT betk.submit_seller_application(
        'CI Submit', 'CI Submit', NULL, 'ci-p09-submit',
        'ci', NULL, 'Cairo', 'Cairo',
        '{}'::jsonb, '{"delivery_fee_egp":15}'::jsonb,
        NULL, NULL, 'ci/front', 'ci/back'
      )
    $sql$
  );
  SELECT count(*)::integer INTO v_n FROM betk.stores WHERE seller_id = v_submit;
  IF v_n <> 0 THEN
    v_msg := v_msg || '|rows';
  END IF;
  PERFORM pg_temp.rec('submit_no_acceptance', 'BETK_SELLER_AGREEMENT_REQUIRED', v_msg);

  v_msg := pg_temp.exec_as(
    v_resubmit,
    'authenticated',
    $sql$SELECT betk.resubmit_seller_application('ci/front2', 'ci/back2')$sql$
  );
  SELECT rejected_reason INTO v_reason
  FROM betk.seller_profiles WHERE id = v_resubmit;
  IF v_reason IS DISTINCT FROM 'ci' THEN
    v_msg := v_msg || '|wrote';
  END IF;
  PERFORM pg_temp.rec('resubmit_no_acceptance', 'BETK_SELLER_AGREEMENT_REQUIRED', v_msg);

  INSERT INTO betk.agreement_acceptances (user_id, document, version_label)
  SELECT u.id, 'seller_agreement', s.value
  FROM betk.users AS u
  CROSS JOIN betk.admin_settings AS s
  WHERE u.id IN (v_submit, v_resubmit)
    AND s.key = 'agreement_seller_agreement_version';

  v_msg := pg_temp.exec_as(
    v_submit,
    'authenticated',
    $sql$
      SELECT betk.submit_seller_application(
        'CI Submit', 'CI Submit', NULL, 'ci-p09-submit',
        'ci', NULL, 'Cairo', 'Cairo',
        '{}'::jsonb, '{"delivery_fee_egp":15}'::jsonb,
        NULL, NULL, 'ci/front', 'ci/back'
      )
    $sql$
  );
  PERFORM pg_temp.rec('submit_accepted', 'ok', v_msg);

  -- REG-65. Non-empty p_delivery_options is not stored.
  SELECT delivery_options::text INTO v_opts
  FROM betk.stores WHERE seller_id = v_submit;
  PERFORM pg_temp.rec('submit_delivery_options', '{}', coalesce(v_opts, 'norow'));

  v_msg := pg_temp.exec_as(
    v_resubmit,
    'authenticated',
    $sql$SELECT betk.resubmit_seller_application('ci/front2', 'ci/back2')$sql$
  );
  IF v_msg = 'ok' THEN
    SELECT rejected_reason INTO v_reason
    FROM betk.seller_profiles WHERE id = v_resubmit;
    IF v_reason IS NOT NULL THEN
      v_msg := 'still_set';
    END IF;
  END IF;
  PERFORM pg_temp.rec('resubmit_accepted', 'ok', v_msg);

  -- P09M2. S1. Postgres inserts (no JWT) are allowed. The seller cases
  -- below use auth.role() = authenticated and users.role = seller.
  INSERT INTO betk.users (id, role, status, phone_number) VALUES
    (v_gate, 'seller', 'active', '01090000007'),
    (v_reset, 'seller', 'active', '01090000008'),
    (v_extra, 'seller', 'active', '01090000009');

  INSERT INTO betk.seller_profiles (id, status, level) VALUES
    (v_gate, 'pending', 'bronze');

  INSERT INTO betk.seller_profiles (id, status, rejected_reason, submitted_at)
  VALUES (v_reset, 'pending', 'ci', timestamptz '2026-01-01 00:00:00+00');

  INSERT INTO betk.stores (
    id, seller_id, name_ar, slug, governorate, city, category_primary, status
  ) VALUES
    (v_gate_store, v_gate, 'CI Gate', 'ci-p09-gate', 'Cairo', 'Cairo', 'ci', 'pending'),
    (v_reset_store, v_reset, 'CI Reset', 'ci-p09-reset', 'Cairo', 'Cairo', 'ci', 'pending');

  INSERT INTO betk.seller_documents (
    seller_id, document_type, storage_path, review_status
  ) VALUES
    (v_gate, 'national_id_front', 'ci/gate-front', 'pending');

  INSERT INTO betk.seller_documents (
    seller_id, document_type, storage_path, review_status, reviewed_at
  ) VALUES
    (v_reset, 'national_id_front', 'ci/reset-front', 'rejected', timestamptz '2026-01-01 00:00:00+00'),
    (v_reset, 'national_id_back', 'ci/reset-back', 'rejected', timestamptz '2026-01-01 00:00:00+00');

  INSERT INTO betk.agreement_acceptances (user_id, document, version_label)
  SELECT v_reset, 'seller_agreement', s.value
  FROM betk.admin_settings AS s
  WHERE s.key = 'agreement_seller_agreement_version';

  -- S1. doc_review_status labels approved and rejected (SELECT 2026-10-04).
  -- Probe 2be9f88 stored approved. P09M2 must refuse both.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.seller_documents SET review_status = %L::betk.doc_review_status
       WHERE seller_id = %L AND document_type = %L::betk.doc_type',
      'approved', v_gate, 'national_id_front'
    )
  );
  PERFORM pg_temp.rec('gate_doc_approved', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.seller_documents SET review_status = %L::betk.doc_review_status
       WHERE seller_id = %L AND document_type = %L::betk.doc_type',
      'rejected', v_gate, 'national_id_front'
    )
  );
  PERFORM pg_temp.rec('gate_doc_rejected', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- S1. reviewed_at is the review stamp. No seller writer except the resubmit null.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.seller_documents SET reviewed_at = %L::timestamptz
       WHERE seller_id = %L AND document_type = %L::betk.doc_type',
      '2026-03-01 00:00:00+00', v_gate, 'national_id_front'
    )
  );
  PERFORM pg_temp.rec('gate_reviewed_at', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- S1. seller_status real labels other than the initial pending
  -- (SELECT 2026-10-04: pending, active, suspended, banned). FR-ADM-2 / R-S04.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.seller_profiles SET status = %L::betk.seller_status WHERE id = %L',
      'active', v_gate
    )
  );
  PERFORM pg_temp.rec('gate_status_active', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.seller_profiles SET status = %L::betk.seller_status WHERE id = %L',
      'suspended', v_gate
    )
  );
  PERFORM pg_temp.rec('gate_status_suspended', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.seller_profiles SET status = %L::betk.seller_status WHERE id = %L',
      'banned', v_gate
    )
  );
  PERFORM pg_temp.rec('gate_status_banned', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- S1. seller_level gold (SELECT 2026-10-04: bronze, silver, gold).
  -- Cron recalculate-seller-levels is the writer. Submit inserts bronze.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.seller_profiles SET level = %L::betk.seller_level WHERE id = %L',
      'gold', v_gate
    )
  );
  PERFORM pg_temp.rec('gate_level_gold', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- S1. store_status real labels other than pending
  -- (SELECT 2026-10-04: pending, active, suspended).
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.stores SET status = %L::betk.store_status WHERE seller_id = %L',
      'active', v_gate
    )
  );
  PERFORM pg_temp.rec('gate_store_active', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.stores SET status = %L::betk.store_status WHERE seller_id = %L',
      'suspended', v_gate
    )
  );
  PERFORM pg_temp.rec('gate_store_suspended', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- S1. Flag found: seller_profiles.is_verified (UI spec VerifiedBadge).
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format('UPDATE betk.seller_profiles SET is_verified = true WHERE id = %L', v_gate)
  );
  PERFORM pg_temp.rec('gate_is_verified', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- FR-ADM-2 approved_at stamp. Probe 2026-10-04 stored the timestamp.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.seller_profiles SET approved_at = %L::timestamptz WHERE id = %L',
      '2026-03-01 00:00:00+00', v_gate
    )
  );
  PERFORM pg_temp.rec('gate_approved_at', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- Cron lift-temp-suspensions writes suspension_ends_at. No seller writer.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.seller_profiles SET suspension_ends_at = %L::timestamptz WHERE id = %L',
      '2026-03-01 00:00:00+00', v_gate
    )
  );
  PERFORM pg_temp.rec('gate_suspension_ends_at', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- S1. rejected_reason is admin text. The seller exception is NULL on resubmit, not a reason.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.seller_profiles SET rejected_reason = %L WHERE id = %L',
      'self', v_gate
    )
  );
  PERFORM pg_temp.rec('gate_rejected_reason', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- S1. submitted_at changes only with the resubmit clear. A lone stamp is refused.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.seller_profiles SET submitted_at = %L::timestamptz WHERE id = %L',
      '2026-03-01 00:00:00+00', v_gate
    )
  );
  PERFORM pg_temp.rec('gate_submitted_at', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- Cron recalculate-seller-levels writes level_score. Probe 2026-10-04 stored 80.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format('UPDATE betk.seller_profiles SET level_score = 40 WHERE id = %L', v_gate)
  );
  PERFORM pg_temp.rec('gate_level_score', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- UI spec admin suspension data. No seller writer. Probe stored 2.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format('UPDATE betk.seller_profiles SET strike_count = 1 WHERE id = %L', v_gate)
  );
  PERFORM pg_temp.rec('gate_strike_count', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- Cron reads total_orders_completed to assign level. Probe stored 50.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format('UPDATE betk.seller_profiles SET total_orders_completed = 50 WHERE id = %L', v_gate)
  );
  PERFORM pg_temp.rec('gate_orders_completed', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- Cron reads total_reviews_count for level_score. Probe stored 9.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format('UPDATE betk.seller_profiles SET total_reviews_count = 9 WHERE id = %L', v_gate)
  );
  PERFORM pg_temp.rec('gate_reviews_count', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- S1. A seller INSERT that asks for a non-pending profile is refused.
  -- submit's insert is the pending exception, proved by submit_accepted plus the reads below.
  v_msg := pg_temp.exec_as(
    v_extra, 'authenticated',
    format(
      'INSERT INTO betk.seller_profiles (id, status, level) VALUES (%L, %L::betk.seller_status, %L::betk.seller_level)',
      v_extra, 'active', 'gold'
    )
  );
  PERFORM pg_temp.rec('gate_profile_insert_active', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  INSERT INTO betk.seller_profiles (id, status, level) VALUES
    (v_extra, 'pending', 'bronze');

  v_msg := pg_temp.exec_as(
    v_extra, 'authenticated',
    format(
      'INSERT INTO betk.stores (
         seller_id, name_ar, slug, governorate, category_primary, status
       ) VALUES (%L, %L, %L, %L, %L, %L::betk.store_status)',
      v_extra, 'CI Extra', 'ci-p09-extra', 'Cairo', 'ci', 'active'
    )
  );
  PERFORM pg_temp.rec('gate_store_insert_active', 'BETK_APPROVAL_STATE_ACTOR', v_msg);

  -- S1. Seller INSERT of seller_documents asking for approved is stored pending,
  -- and reviewed_at is stored null. Same shape as the approved_at stamp.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'INSERT INTO betk.seller_documents (
         seller_id, document_type, storage_path, review_status, reviewed_at
       ) VALUES (%L, %L::betk.doc_type, %L, %L::betk.doc_review_status, %L::timestamptz)',
      v_gate, 'food_packaging', 'ci/force', 'approved', '2026-03-01 00:00:00+00'
    )
  );
  IF v_msg <> 'ok' THEN
    v_opts := v_msg;
  ELSE
    SELECT review_status::text || '|' || CASE WHEN reviewed_at IS NULL THEN 'null' ELSE 'set' END
    INTO v_opts
    FROM betk.seller_documents
    WHERE seller_id = v_gate AND document_type = 'food_packaging';
    v_opts := coalesce(v_opts, 'norow');
  END IF;
  PERFORM pg_temp.rec('doc_insert_forced_pending', 'pending|null', v_opts);

  -- S1. submit inserts seller_profiles and stores pending, and documents pending.
  -- submit_accepted already requires the RPC to return ok. These reads are the stored state.
  SELECT status::text INTO v_opts FROM betk.seller_profiles WHERE id = v_submit;
  PERFORM pg_temp.rec('onboard_profile_pending', 'pending', coalesce(v_opts, 'norow'));

  SELECT status::text INTO v_opts FROM betk.stores WHERE seller_id = v_submit;
  PERFORM pg_temp.rec('onboard_store_pending', 'pending', coalesce(v_opts, 'norow'));

  SELECT CASE
    WHEN count(*) = 2 AND bool_and(review_status = 'pending') AND bool_and(reviewed_at IS NULL)
      THEN 'pending'
    ELSE 'other'
  END
  INTO v_opts
  FROM betk.seller_documents
  WHERE seller_id = v_submit;
  PERFORM pg_temp.rec('onboard_docs_pending', 'pending', coalesce(v_opts, 'norow'));

  -- S1. resubmit resets review_status to pending, reviewed_at to null,
  -- rejected_reason to null, and submitted_at to now(). Live function body.
  v_msg := pg_temp.exec_as(
    v_reset, 'authenticated',
    $sql$SELECT betk.resubmit_seller_application('ci/reset-front-2', 'ci/reset-back-2')$sql$
  );
  IF v_msg <> 'ok' THEN
    v_opts := v_msg;
  ELSE
    SELECT CASE
      WHEN rejected_reason IS NULL AND submitted_at IS DISTINCT FROM timestamptz '2026-01-01 00:00:00+00'
        THEN 'cleared'
      ELSE 'kept'
    END
    INTO v_opts
    FROM betk.seller_profiles
    WHERE id = v_reset;
    v_opts := coalesce(v_opts, 'norow');
  END IF;
  PERFORM pg_temp.rec('resubmit_profile_cleared', 'cleared', v_opts);

  IF v_msg <> 'ok' THEN
    v_opts := v_msg;
  ELSE
    SELECT CASE
      WHEN count(*) = 2
       AND bool_and(review_status = 'pending')
       AND bool_and(reviewed_at IS NULL)
        THEN 'pending'
      ELSE 'other'
    END
    INTO v_opts
    FROM betk.seller_documents
    WHERE seller_id = v_reset;
    v_opts := coalesce(v_opts, 'norow');
  END IF;
  PERFORM pg_temp.rec('resubmit_docs_pending', 'pending', v_opts);

  -- Seller-editable. recomputeSellerAvgResponseHours writes this column
  -- on the seller session. The trigger must not refuse it.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format('UPDATE betk.seller_profiles SET avg_response_hours = 1.25 WHERE id = %L', v_gate)
  );
  IF v_msg = 'ok' THEN
    SELECT CASE
      WHEN avg_response_hours = 1.25 THEN '1.25'
      ELSE coalesce(avg_response_hours::text, 'null')
    END
    INTO v_opts
    FROM betk.seller_profiles WHERE id = v_gate;
    IF v_opts IS DISTINCT FROM '1.25' THEN
      v_msg := v_opts;
    END IF;
  END IF;
  PERFORM pg_temp.rec('seller_avg_response', 'ok', v_msg);

  -- updateStoreProfile writes name_ar and does not write status.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format('UPDATE betk.stores SET name_ar = %L WHERE seller_id = %L', 'CI renamed', v_gate)
  );
  IF v_msg = 'ok' THEN
    SELECT name_ar INTO v_opts FROM betk.stores WHERE seller_id = v_gate;
    IF v_opts IS DISTINCT FROM 'CI renamed' THEN
      v_msg := coalesce(v_opts, 'null');
    END IF;
  END IF;
  PERFORM pg_temp.rec('seller_store_name', 'ok', v_msg);

  -- Resubmit and the food upsert write storage_path. Pending/null stays pending/null.
  v_msg := pg_temp.exec_as(
    v_gate, 'authenticated',
    format(
      'UPDATE betk.seller_documents SET storage_path = %L
       WHERE seller_id = %L AND document_type = %L::betk.doc_type',
      'ci/gate-front-2', v_gate, 'national_id_front'
    )
  );
  IF v_msg = 'ok' THEN
    SELECT review_status::text INTO v_opts
    FROM betk.seller_documents
    WHERE seller_id = v_gate AND document_type = 'national_id_front';
    IF v_opts IS DISTINCT FROM 'pending' THEN
      v_msg := coalesce(v_opts, 'null');
    END IF;
  END IF;
  PERFORM pg_temp.rec('seller_doc_path', 'ok', v_msg);

  -- S1. Admin approve. users.role admin, JWT role authenticated, is_admin() true.
  v_msg := pg_temp.exec_as(
    v_admin, 'authenticated',
    format(
      'UPDATE betk.seller_profiles
       SET status = %L::betk.seller_status, approved_at = %L::timestamptz
       WHERE id = %L',
      'active', '2026-04-01 00:00:00+00', v_gate
    )
  );
  IF v_msg = 'ok' THEN
    v_msg := pg_temp.exec_as(
      v_admin, 'authenticated',
      format(
        'UPDATE betk.stores SET status = %L::betk.store_status WHERE seller_id = %L',
        'active', v_gate
      )
    );
  END IF;
  IF v_msg = 'ok' THEN
    v_msg := pg_temp.exec_as(
      v_admin, 'authenticated',
      format(
        'UPDATE betk.seller_documents
         SET review_status = %L::betk.doc_review_status, reviewed_at = %L::timestamptz
         WHERE seller_id = %L AND document_type = %L::betk.doc_type',
        'approved', '2026-04-01 00:00:00+00', v_gate, 'national_id_front'
      )
    );
  END IF;
  IF v_msg = 'ok' THEN
    SELECT p.status::text || '|' || s.status::text || '|' || d.review_status::text
    INTO v_opts
    FROM betk.seller_profiles AS p
    JOIN betk.stores AS s ON s.seller_id = p.id
    JOIN betk.seller_documents AS d
      ON d.seller_id = p.id AND d.document_type = 'national_id_front'
    WHERE p.id = v_gate;
    IF v_opts IS DISTINCT FROM 'active|active|approved' THEN
      v_msg := coalesce(v_opts, 'norow');
    END IF;
  END IF;
  PERFORM pg_temp.rec('admin_approve', 'ok', v_msg);

  -- S1. Admin reject. Document rejected, and the profile reason is stored.
  v_msg := pg_temp.exec_as(
    v_admin, 'authenticated',
    format(
      'UPDATE betk.seller_documents
       SET review_status = %L::betk.doc_review_status, reviewed_at = %L::timestamptz
       WHERE seller_id = %L AND document_type = %L::betk.doc_type',
      'rejected', '2026-04-02 00:00:00+00', v_gate, 'national_id_front'
    )
  );
  IF v_msg = 'ok' THEN
    v_msg := pg_temp.exec_as(
      v_admin, 'authenticated',
      format(
        'UPDATE betk.seller_profiles
         SET status = %L::betk.seller_status, rejected_reason = %L
         WHERE id = %L',
        'pending', 'no', v_gate
      )
    );
  END IF;
  IF v_msg = 'ok' THEN
    SELECT d.review_status::text || '|' || coalesce(p.rejected_reason, 'null')
    INTO v_opts
    FROM betk.seller_profiles AS p
    JOIN betk.seller_documents AS d
      ON d.seller_id = p.id AND d.document_type = 'national_id_front'
    WHERE p.id = v_gate;
    IF v_opts IS DISTINCT FROM 'rejected|no' THEN
      v_msg := coalesce(v_opts, 'norow');
    END IF;
  END IF;
  PERFORM pg_temp.rec('admin_reject', 'ok', v_msg);

  -- S1. Service role JWT is not 'authenticated'. SET ROLE service_role.
  v_msg := pg_temp.exec_as(
    v_gate, 'service_role',
    format('UPDATE betk.seller_profiles SET is_verified = true WHERE id = %L', v_gate)
  );
  IF v_msg = 'ok' THEN
    SELECT CASE WHEN is_verified THEN 'true' ELSE 'false' END
    INTO v_opts
    FROM betk.seller_profiles WHERE id = v_gate;
    IF v_opts IS DISTINCT FROM 'true' THEN
      v_msg := coalesce(v_opts, 'null');
    END IF;
  END IF;
  PERFORM pg_temp.rec('service_role_verify', 'ok', v_msg);

  -- S1. No JWT. This DO block runs as postgres. auth.role() is null.
  v_msg := pg_temp.try_exec(format(
    'UPDATE betk.seller_profiles SET level = %L::betk.seller_level WHERE id = %L',
    'silver', v_gate
  ));
  IF v_msg = 'ok' THEN
    SELECT level::text INTO v_opts FROM betk.seller_profiles WHERE id = v_gate;
    IF v_opts IS DISTINCT FROM 'silver' THEN
      v_msg := coalesce(v_opts, 'null');
    END IF;
  END IF;
  PERFORM pg_temp.rec('postgres_level', 'ok', v_msg);
END;
$cases$;

INSERT INTO p09_results (name, expected, actual, pass)
SELECT
  'all_pass',
  'true|59',
  bool_and(pass)::text || '|' || count(*)::text,
  bool_and(pass) AND count(*) = 59
FROM p09_results;

SELECT name, expected, actual, pass
FROM p09_results
ORDER BY ord;

COMMIT;
