-- T05b CI proof. One result set: name, expected, actual, pass.
-- Cases cite plan §1.5–§1.7, §6 M7/M8, §8.2.5, ERD §6–§8, R-O17, ADR-022,
-- ADR-020 / REG-90, ADR-021, ADR-023. CI pins are labelled CI TEST VALUE
-- (R2). They are not staging values.
-- CASE_COUNT 58. all_pass checks that count. Do not change an expected
-- value to match a wrong actual.

SET TIME ZONE 'UTC';

BEGIN;

CREATE TEMP TABLE m78_results (
  ord integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  expected text,
  actual text,
  pass boolean NOT NULL
) ON COMMIT DROP;

CREATE FUNCTION pg_temp.rec(p_name text, p_expected text, p_actual text)
RETURNS void
LANGUAGE plpgsql
AS $rec$
BEGIN
  INSERT INTO m78_results (name, expected, actual, pass)
  VALUES (p_name, p_expected, p_actual, p_expected IS NOT DISTINCT FROM p_actual);
END;
$rec$;

CREATE FUNCTION pg_temp.checkout_as(p_uid uuid, p_address uuid)
RETURNS text
LANGUAGE plpgsql
AS $checkout$
DECLARE
  v_msg text;
BEGIN
  PERFORM set_config('request.jwt.claim.sub', p_uid::text, true);
  PERFORM set_config(
    'request.jwt.claims',
    json_build_object('sub', p_uid, 'role', 'authenticated')::text,
    true
  );
  EXECUTE 'SET ROLE authenticated';
  BEGIN
    PERFORM betk.checkout_from_cart(p_address);
    v_msg := 'ok';
  EXCEPTION WHEN OTHERS THEN
    v_msg := SQLERRM;
  END;
  EXECUTE 'RESET ROLE';
  PERFORM set_config('request.jwt.claim.sub', '', true);
  PERFORM set_config('request.jwt.claims', '{}', true);
  RETURN v_msg;
END;
$checkout$;

CREATE FUNCTION pg_temp.exec_as(p_uid uuid, p_role text, p_sql text)
RETURNS text
LANGUAGE plpgsql
AS $exec$
DECLARE
  v_msg text;
BEGIN
  IF p_uid IS NULL THEN
    PERFORM set_config('request.jwt.claim.sub', '', true);
    PERFORM set_config('request.jwt.claims', '{}', true);
  ELSE
    PERFORM set_config('request.jwt.claim.sub', p_uid::text, true);
    PERFORM set_config(
      'request.jwt.claims',
      json_build_object('sub', p_uid, 'role', p_role)::text,
      true
    );
  END IF;
  EXECUTE format('SET ROLE %I', p_role);
  BEGIN
    EXECUTE p_sql;
    v_msg := 'ok';
  EXCEPTION WHEN OTHERS THEN
    v_msg := SQLERRM;
  END;
  EXECUTE 'RESET ROLE';
  PERFORM set_config('request.jwt.claim.sub', '', true);
  PERFORM set_config('request.jwt.claims', '{}', true);
  RETURN v_msg;
END;
$exec$;

CREATE FUNCTION pg_temp.scalar_as(p_uid uuid, p_role text, p_sql text)
RETURNS text
LANGUAGE plpgsql
AS $scalar$
DECLARE
  v_val text;
  v_msg text;
BEGIN
  PERFORM set_config('request.jwt.claim.sub', p_uid::text, true);
  PERFORM set_config(
    'request.jwt.claims',
    json_build_object('sub', p_uid, 'role', p_role)::text,
    true
  );
  EXECUTE format('SET ROLE %I', p_role);
  BEGIN
    EXECUTE p_sql INTO v_val;
    IF NOT FOUND THEN
      v_msg := 'norow';
    ELSE
      v_msg := v_val;
    END IF;
  EXCEPTION WHEN OTHERS THEN
    v_msg := SQLERRM;
  END;
  EXECUTE 'RESET ROLE';
  PERFORM set_config('request.jwt.claim.sub', '', true);
  PERFORM set_config('request.jwt.claims', '{}', true);
  RETURN v_msg;
END;
$scalar$;

-- Fixed ids. Not staging ids. Phones are synthetic.
INSERT INTO betk.users (id, role, status, phone_number) VALUES
  ('a1000000-0000-4000-8000-000000000001', 'buyer', 'active', '01011110001'),
  ('a1000000-0000-4000-8000-000000000002', 'seller', 'active', '01011110002'),
  ('a1000000-0000-4000-8000-000000000003', 'seller', 'active', '01011110003'),
  ('a1000000-0000-4000-8000-000000000004', 'admin', 'active', '01011110004'),
  ('a1000000-0000-4000-8000-000000000005', 'buyer', 'active', NULL),
  ('a1000000-0000-4000-8000-000000000006', 'buyer', 'active', '01011110006'),
  ('a1000000-0000-4000-8000-000000000007', 'buyer', 'active', '01011110007'),
  ('a1000000-0000-4000-8000-000000000008', 'buyer', 'active', '01011110008'),
  ('a1000000-0000-4000-8000-000000000009', 'buyer', 'active', '01011110009'),
  ('a1000000-0000-4000-8000-00000000000a', 'buyer', 'active', '01011110010'),
  ('a1000000-0000-4000-8000-00000000000b', 'buyer', 'active', '01011110011'),
  ('a1000000-0000-4000-8000-00000000000c', 'buyer', 'active', '01011110012'),
  ('a1000000-0000-4000-8000-00000000000d', 'buyer', 'active', '01011110013'),
  ('a1000000-0000-4000-8000-00000000000e', 'buyer', 'active', '01011110014'),
  ('a1000000-0000-4000-8000-00000000000f', 'buyer', 'active', '01011110015'),
  ('a1000000-0000-4000-8000-000000000010', 'buyer', 'active', '01011110016'),
  ('a1000000-0000-4000-8000-000000000011', 'buyer', 'active', '01011110017'),
  ('a1000000-0000-4000-8000-000000000012', 'buyer', 'active', '01011110018');

INSERT INTO betk.seller_profiles (id, status) VALUES
  ('a1000000-0000-4000-8000-000000000002', 'active'),
  ('a1000000-0000-4000-8000-000000000003', 'active');

INSERT INTO betk.stores (
  id, seller_id, name_ar, slug, governorate, city, category_primary, status
) VALUES
  (
    'a2000000-0000-4000-8000-000000000001',
    'a1000000-0000-4000-8000-000000000002',
    'CI Cairo', 'ci-cairo', 'Cairo', 'Cairo', 'ci', 'active'
  ),
  (
    'a2000000-0000-4000-8000-000000000002',
    'a1000000-0000-4000-8000-000000000003',
    'CI Giza', 'ci-giza', 'Giza', 'Giza', 'ci', 'active'
  );

INSERT INTO betk.listings (
  id, store_id, category_id, title_ar, type, price_type, price,
  stock_qty, status, weight_g, length_mm, width_mm, height_mm, prep_days
)
SELECT
  v.id, v.store_id, c.id, v.title_ar, 'product', 'fixed', v.price,
  v.stock_qty, v.status::betk.listing_status,
  v.weight_g, v.length_mm, v.width_mm, v.height_mm, v.prep_days
FROM (
  VALUES
    (
      'a3000000-0000-4000-8000-000000000001'::uuid,
      'a2000000-0000-4000-8000-000000000001'::uuid,
      'CI A', 100::numeric, 20, 'active', 500, 100, 100, 100, 1::smallint
    ),
    (
      'a3000000-0000-4000-8000-000000000002'::uuid,
      'a2000000-0000-4000-8000-000000000002'::uuid,
      'CI B', 100::numeric, 20, 'active', 1500, 100, 100, 100, 1::smallint
    ),
    (
      'a3000000-0000-4000-8000-000000000003'::uuid,
      'a2000000-0000-4000-8000-000000000001'::uuid,
      'CI draft', 100::numeric, NULL::integer, 'draft',
      NULL::integer, NULL::integer, NULL::integer, NULL::integer, NULL::smallint
    ),
    (
      'a3000000-0000-4000-8000-000000000004'::uuid,
      'a2000000-0000-4000-8000-000000000001'::uuid,
      'CI oos', 100::numeric, 1, 'active', 500, 100, 100, 100, 1::smallint
    )
) AS v(
  id, store_id, title_ar, price, stock_qty, status,
  weight_g, length_mm, width_mm, height_mm, prep_days
)
CROSS JOIN LATERAL (
  SELECT id
  FROM betk.categories
  WHERE is_active
  ORDER BY slug
  LIMIT 1
) AS c;

INSERT INTO betk.addresses (id, buyer_id, governorate, city, street_address)
SELECT
  v.id,
  v.buyer_id,
  v.governorate,
  'CI',
  'CI street'
FROM (
  VALUES
    ('a4000000-0000-4000-8000-000000000001'::uuid, 'a1000000-0000-4000-8000-000000000001'::uuid, 'Alexandria'),
    ('a4000000-0000-4000-8000-000000000005'::uuid, 'a1000000-0000-4000-8000-000000000005'::uuid, 'Alexandria'),
    ('a4000000-0000-4000-8000-000000000006'::uuid, 'a1000000-0000-4000-8000-000000000006'::uuid, 'Alexandria'),
    ('a4000000-0000-4000-8000-000000000007'::uuid, 'a1000000-0000-4000-8000-000000000007'::uuid, 'Alexandria'),
    ('a4000000-0000-4000-8000-000000000008'::uuid, 'a1000000-0000-4000-8000-000000000008'::uuid, 'Aswan'),
    ('a4000000-0000-4000-8000-000000000009'::uuid, 'a1000000-0000-4000-8000-000000000009'::uuid, 'Alexandria'),
    ('a4000000-0000-4000-8000-00000000000a'::uuid, 'a1000000-0000-4000-8000-00000000000a'::uuid, 'Alexandria'),
    ('a4000000-0000-4000-8000-00000000000b'::uuid, 'a1000000-0000-4000-8000-00000000000b'::uuid, 'Alexandria'),
    ('a4000000-0000-4000-8000-00000000000c'::uuid, 'a1000000-0000-4000-8000-00000000000c'::uuid, 'Alexandria'),
    ('a4000000-0000-4000-8000-00000000000d'::uuid, 'a1000000-0000-4000-8000-00000000000d'::uuid, 'Alexandria'),
    ('a4000000-0000-4000-8000-00000000000e'::uuid, 'a1000000-0000-4000-8000-00000000000e'::uuid, 'Alexandria'),
    ('a4000000-0000-4000-8000-00000000000f'::uuid, 'a1000000-0000-4000-8000-00000000000f'::uuid, 'Alexandria'),
    ('a4000000-0000-4000-8000-000000000010'::uuid, 'a1000000-0000-4000-8000-000000000010'::uuid, 'Alexandria'),
    ('a4000000-0000-4000-8000-000000000011'::uuid, 'a1000000-0000-4000-8000-000000000011'::uuid, 'Alexandria')
) AS v(id, buyer_id, governorate);

INSERT INTO betk.courier_rates (
  id, origin_governorate, destination_governorate, weight_min_g, weight_max_g, fee_egp
) VALUES
  ('a5000000-0000-4000-8000-000000000001', 'Cairo', 'Alexandria', 0, 1000, 20),
  ('a5000000-0000-4000-8000-000000000002', 'Cairo', 'Alexandria', 1000, NULL, 40),
  ('a5000000-0000-4000-8000-000000000003', 'Giza', 'Alexandria', 0, NULL, 30);

INSERT INTO betk.inquiries (
  id, buyer_id, store_id, listing_id, buyer_first_message,
  quoted_price, quoted_prep_days, quote_expires_at
) VALUES
  (
    'a6000000-0000-4000-8000-000000000001',
    'a1000000-0000-4000-8000-000000000001',
    'a2000000-0000-4000-8000-000000000002',
    'a3000000-0000-4000-8000-000000000002',
    'ci', 150, 1, now() + interval '24 hours'
  ),
  (
    'a6000000-0000-4000-8000-000000000002',
    'a1000000-0000-4000-8000-00000000000a',
    'a2000000-0000-4000-8000-000000000002',
    'a3000000-0000-4000-8000-000000000002',
    'ci', 150, 1, now() - interval '1 hour'
  ),
  (
    'a6000000-0000-4000-8000-000000000003',
    'a1000000-0000-4000-8000-00000000000b',
    'a2000000-0000-4000-8000-000000000002',
    'a3000000-0000-4000-8000-000000000002',
    'ci', 250, 1, now() + interval '24 hours'
  );

INSERT INTO betk.cart_items (buyer_id, listing_id, quantity, unit_price, is_custom, inquiry_id)
VALUES
  ('a1000000-0000-4000-8000-000000000001', 'a3000000-0000-4000-8000-000000000001', 1, 100, false, NULL),
  ('a1000000-0000-4000-8000-000000000001', 'a3000000-0000-4000-8000-000000000002', 1, 150, true, 'a6000000-0000-4000-8000-000000000001'),
  ('a1000000-0000-4000-8000-000000000006', 'a3000000-0000-4000-8000-000000000001', 1, 100, false, NULL),
  ('a1000000-0000-4000-8000-000000000007', 'a3000000-0000-4000-8000-000000000003', 1, 100, false, NULL),
  ('a1000000-0000-4000-8000-000000000008', 'a3000000-0000-4000-8000-000000000001', 1, 100, false, NULL),
  ('a1000000-0000-4000-8000-000000000009', 'a3000000-0000-4000-8000-000000000004', 2, 100, false, NULL),
  ('a1000000-0000-4000-8000-00000000000a', 'a3000000-0000-4000-8000-000000000002', 1, 150, true, 'a6000000-0000-4000-8000-000000000002'),
  ('a1000000-0000-4000-8000-00000000000b', 'a3000000-0000-4000-8000-000000000002', 1, 250, true, 'a6000000-0000-4000-8000-000000000003'),
  ('a1000000-0000-4000-8000-000000000005', 'a3000000-0000-4000-8000-000000000001', 1, 100, false, NULL),
  ('a1000000-0000-4000-8000-00000000000c', 'a3000000-0000-4000-8000-000000000001', 1, 100, false, NULL),
  ('a1000000-0000-4000-8000-00000000000d', 'a3000000-0000-4000-8000-000000000001', 1, 100, false, NULL),
  ('a1000000-0000-4000-8000-00000000000d', 'a3000000-0000-4000-8000-000000000002', 1, 100, false, NULL),
  ('a1000000-0000-4000-8000-00000000000e', 'a3000000-0000-4000-8000-000000000001', 1, 100, false, NULL),
  ('a1000000-0000-4000-8000-00000000000f', 'a3000000-0000-4000-8000-000000000001', 1, 100, false, NULL),
  ('a1000000-0000-4000-8000-000000000010', 'a3000000-0000-4000-8000-000000000001', 1, 100, false, NULL),
  ('a1000000-0000-4000-8000-000000000011', 'a3000000-0000-4000-8000-000000000001', 1, 100, false, NULL);

-- R2. CI TEST VALUE. Not applied to staging. Empty agreement keys stay empty.
UPDATE betk.admin_settings
SET value = '30', description = 'CI TEST VALUE'
WHERE key = 'payment_window_minutes';

UPDATE betk.admin_settings
SET value = '2', description = 'CI TEST VALUE'
WHERE key = 'quote_tolerance_multiplier';

UPDATE betk.admin_settings
SET value = '24', description = 'CI TEST VALUE'
WHERE key = 'quote_validity_hours';

UPDATE betk.admin_settings
SET value = '10', description = 'CI TEST VALUE'
WHERE key = 'commission_rate_pct';

UPDATE betk.admin_settings
SET value = '24', description = 'CI TEST VALUE'
WHERE key = 'return_hold_hours';

UPDATE betk.admin_settings
SET value = '3', description = 'CI TEST VALUE'
WHERE key = 'seller_category_limit';

DO $cases$
DECLARE
  v_happy uuid := 'a1000000-0000-4000-8000-000000000001';
  v_seller_cairo uuid := 'a1000000-0000-4000-8000-000000000002';
  v_admin uuid := 'a1000000-0000-4000-8000-000000000004';
  v_nophone uuid := 'a1000000-0000-4000-8000-000000000005';
  v_window uuid := 'a1000000-0000-4000-8000-000000000006';
  v_weight uuid := 'a1000000-0000-4000-8000-000000000007';
  v_rate uuid := 'a1000000-0000-4000-8000-000000000008';
  v_stock_buyer uuid := 'a1000000-0000-4000-8000-000000000009';
  v_expired uuid := 'a1000000-0000-4000-8000-00000000000a';
  v_band uuid := 'a1000000-0000-4000-8000-00000000000b';
  v_deadline uuid := 'a1000000-0000-4000-8000-00000000000c';
  v_release uuid := 'a1000000-0000-4000-8000-00000000000d';
  v_cancel uuid := 'a1000000-0000-4000-8000-00000000000e';
  v_expiry uuid := 'a1000000-0000-4000-8000-00000000000f';
  v_return uuid := 'a1000000-0000-4000-8000-000000000010';
  v_illegal uuid := 'a1000000-0000-4000-8000-000000000011';
  v_payout_buyer uuid := 'a1000000-0000-4000-8000-000000000012';
  v_store_cairo uuid := 'a2000000-0000-4000-8000-000000000001';
  v_list_a uuid := 'a3000000-0000-4000-8000-000000000001';
  v_list_b uuid := 'a3000000-0000-4000-8000-000000000002';
  v_list_oos uuid := 'a3000000-0000-4000-8000-000000000004';
  v_msg text;
  v_show text;
  v_m text;
  v_s text;
  v_c text;
  v_extra text;
  v_master uuid;
  v_order uuid;
  v_pay uuid;
  v_before integer;
  v_after integer;
  v_walk text;
  v_c1 uuid;
  v_c2 uuid;
  v_c3 uuid;
  v_c4 uuid;
  v_def text;
BEGIN
  -- Grants. Plan §1.6, §6 M7, ADR-020, REG-90, E1.
  PERFORM pg_temp.rec(
    'so_select_columns',
    'id,betk_ref,buyer_id,store_id,inquiry_id,delivery_address_id,delivery_method,subtotal,status,cancelled_by,cancellation_reason,notes,created_at,confirmed_at,delivered_at,commission_rate,commission_amount,master_order_id,display_ref,courier_rate_id,prep_deadline,escalated_at,escalation_reason,escalation_note,escalation_resolved_at,balance_confirmed_at,refunded_subtotal,payout_eligible_at',
    (
      SELECT string_agg(c.column_name, ',' ORDER BY c.ordinal_position)
      FROM information_schema.columns AS c
      WHERE c.table_schema = 'betk'
        AND c.table_name = 'seller_orders'
        AND has_column_privilege('authenticated', 'betk.seller_orders', c.column_name, 'SELECT')
    )
  );
  PERFORM pg_temp.rec(
    'so_no_delivery_fee',
    'false',
    has_column_privilege('authenticated', 'betk.seller_orders', 'delivery_fee', 'SELECT')::text
  );
  PERFORM pg_temp.rec(
    'so_no_total_amount',
    'false',
    has_column_privilege('authenticated', 'betk.seller_orders', 'total_amount', 'SELECT')::text
  );
  PERFORM pg_temp.rec(
    'so_has_refunded_subtotal',
    'true',
    has_column_privilege('authenticated', 'betk.seller_orders', 'refunded_subtotal', 'SELECT')::text
  );
  PERFORM pg_temp.rec(
    'anon_so_select_false',
    'false',
    has_table_privilege('anon', 'betk.seller_orders', 'SELECT')::text
  );
  PERFORM pg_temp.rec(
    'mo_insert_columns',
    'buyer_id,betk_ref,delivery_address_id,recipient_name,recipient_phone,snapshot_governorate,snapshot_city,snapshot_street_address,snapshot_building_notes,combined_delivery_total,payment_deadline',
    (
      SELECT string_agg(c.column_name, ',' ORDER BY c.ordinal_position)
      FROM information_schema.columns AS c
      WHERE c.table_schema = 'betk'
        AND c.table_name = 'master_orders'
        AND has_column_privilege('authenticated', 'betk.master_orders', c.column_name, 'INSERT')
    )
  );
  PERFORM pg_temp.rec(
    'mo_update_columns',
    'proof_path,transfer_reference',
    (
      SELECT string_agg(c.column_name, ',' ORDER BY c.ordinal_position)
      FROM information_schema.columns AS c
      WHERE c.table_schema = 'betk'
        AND c.table_name = 'master_orders'
        AND has_column_privilege('authenticated', 'betk.master_orders', c.column_name, 'UPDATE')
    )
  );
  PERFORM pg_temp.rec(
    'anon_mo_privileges',
    'false|false|false|false',
    has_table_privilege('anon', 'betk.master_orders', 'SELECT')::text
      || '|' || has_table_privilege('anon', 'betk.master_orders', 'INSERT')::text
      || '|' || has_table_privilege('anon', 'betk.master_orders', 'UPDATE')::text
      || '|' || has_table_privilege('anon', 'betk.master_orders', 'DELETE')::text
  );
  PERFORM pg_temp.rec(
    'checkout_exec_authenticated',
    'true',
    has_function_privilege('authenticated', 'betk.checkout_from_cart(uuid)', 'EXECUTE')::text
  );
  PERFORM pg_temp.rec(
    'checkout_exec_anon',
    'false',
    has_function_privilege('anon', 'betk.checkout_from_cart(uuid)', 'EXECUTE')::text
  );
  PERFORM pg_temp.rec(
    'checkout_exec_public',
    'false',
    has_function_privilege('public', 'betk.checkout_from_cart(uuid)', 'EXECUTE')::text
  );
  PERFORM pg_temp.rec(
    'sessions_policies',
    '0',
    (
      SELECT count(*)::text
      FROM pg_policy AS p
      JOIN pg_class AS c ON c.oid = p.polrelid
      JOIN pg_namespace AS n ON n.oid = c.relnamespace
      WHERE n.nspname = 'betk' AND c.relname = 'sessions'
    )
  );
  PERFORM pg_temp.rec(
    'otp_tokens_policies',
    '0',
    (
      SELECT count(*)::text
      FROM pg_policy AS p
      JOIN pg_class AS c ON c.oid = p.polrelid
      JOIN pg_namespace AS n ON n.oid = c.relnamespace
      WHERE n.nspname = 'betk' AND c.relname = 'otp_tokens'
    )
  );
  PERFORM pg_temp.rec(
    'modlog_admin_insert',
    '1',
    (
      SELECT count(*)::text
      FROM pg_policy AS p
      JOIN pg_class AS c ON c.oid = p.polrelid
      JOIN pg_namespace AS n ON n.oid = c.relnamespace
      WHERE n.nspname = 'betk'
        AND c.relname = 'moderation_logs'
        AND p.polname = 'modlog_admin_insert'
    )
  );
  PERFORM pg_temp.rec(
    'rls_no_policy_count',
    '2',
    (
      SELECT count(*)::text
      FROM pg_class AS c
      JOIN pg_namespace AS n ON n.oid = c.relnamespace
      WHERE n.nspname = 'betk'
        AND c.relkind = 'r'
        AND c.relrowsecurity
        AND NOT EXISTS (SELECT 1 FROM pg_policy AS p WHERE p.polrelid = c.oid)
    )
  );
  PERFORM pg_temp.rec(
    'rls_no_policy_names',
    'otp_tokens,sessions',
    (
      SELECT string_agg(c.relname, ',' ORDER BY c.relname)
      FROM pg_class AS c
      JOIN pg_namespace AS n ON n.oid = c.relnamespace
      WHERE n.nspname = 'betk'
        AND c.relkind = 'r'
        AND c.relrowsecurity
        AND NOT EXISTS (SELECT 1 FROM pg_policy AS p WHERE p.polrelid = c.oid)
    )
  );
  SELECT pg_get_functiondef('betk.checkout_from_cart(uuid)'::regprocedure) INTO v_def;
  PERFORM pg_temp.rec(
    'checkout_invoker_search_path',
    'invoker|pinned',
    (
      SELECT CASE WHEN p.prosecdef THEN 'definer' ELSE 'invoker' END
        || '|' || CASE
          WHEN EXISTS (
            SELECT 1
            FROM unnest(p.proconfig) AS cfg
            WHERE cfg LIKE 'search_path=%'
              AND cfg LIKE '%betk%'
              AND cfg LIKE '%public%'
          ) THEN 'pinned'
          ELSE coalesce(array_to_string(p.proconfig, ';'), 'none')
        END
      FROM pg_proc AS p
      JOIN pg_namespace AS n ON n.oid = p.pronamespace
      WHERE n.nspname = 'betk' AND p.proname = 'checkout_from_cart'
    )
  );

  -- Fail closed. Plan §8.2.5, phone gate plan §2.3. Zero rows each.
  UPDATE betk.admin_settings SET value = '' WHERE key = 'payment_window_minutes';
  v_msg := pg_temp.checkout_as(v_window, 'a4000000-0000-4000-8000-000000000006');
  UPDATE betk.admin_settings
  SET value = '30', description = 'CI TEST VALUE'
  WHERE key = 'payment_window_minutes';
  SELECT count(*)::text INTO v_m FROM betk.master_orders WHERE buyer_id = v_window;
  SELECT count(*)::text INTO v_s FROM betk.seller_orders WHERE buyer_id = v_window;
  SELECT count(*)::text INTO v_c FROM betk.cart_items WHERE buyer_id = v_window;
  PERFORM pg_temp.rec(
    'fail_empty_window',
    'BETK_PAYMENT_WINDOW_UNCONFIGURED|0|0|1',
    v_msg || '|' || v_m || '|' || v_s || '|' || v_c
  );

  v_msg := pg_temp.checkout_as(v_weight, 'a4000000-0000-4000-8000-000000000007');
  SELECT count(*)::text INTO v_m FROM betk.master_orders WHERE buyer_id = v_weight;
  SELECT count(*)::text INTO v_s FROM betk.seller_orders WHERE buyer_id = v_weight;
  SELECT count(*)::text INTO v_c FROM betk.cart_items WHERE buyer_id = v_weight;
  PERFORM pg_temp.rec(
    'fail_null_weight',
    'BETK_CHECKOUT_LINE_UNRESOLVED|0|0|1',
    v_msg || '|' || v_m || '|' || v_s || '|' || v_c
  );

  v_msg := pg_temp.checkout_as(v_rate, 'a4000000-0000-4000-8000-000000000008');
  SELECT count(*)::text INTO v_m FROM betk.master_orders WHERE buyer_id = v_rate;
  SELECT count(*)::text INTO v_s FROM betk.seller_orders WHERE buyer_id = v_rate;
  SELECT count(*)::text INTO v_c FROM betk.cart_items WHERE buyer_id = v_rate;
  PERFORM pg_temp.rec(
    'fail_missing_rate',
    'BETK_CHECKOUT_RATE_MISSING|0|0|1',
    v_msg || '|' || v_m || '|' || v_s || '|' || v_c
  );

  v_msg := pg_temp.checkout_as(v_stock_buyer, 'a4000000-0000-4000-8000-000000000009');
  SELECT count(*)::text INTO v_m FROM betk.master_orders WHERE buyer_id = v_stock_buyer;
  SELECT count(*)::text INTO v_s FROM betk.seller_orders WHERE buyer_id = v_stock_buyer;
  SELECT count(*)::text INTO v_c FROM betk.cart_items WHERE buyer_id = v_stock_buyer;
  SELECT stock_qty::text INTO v_extra FROM betk.listings WHERE id = v_list_oos;
  PERFORM pg_temp.rec(
    'fail_out_of_stock',
    'BETK_CHECKOUT_OUT_OF_STOCK|0|0|1|1',
    v_msg || '|' || v_m || '|' || v_s || '|' || v_c || '|' || v_extra
  );

  v_msg := pg_temp.checkout_as(v_expired, 'a4000000-0000-4000-8000-00000000000a');
  SELECT count(*)::text INTO v_m FROM betk.master_orders WHERE buyer_id = v_expired;
  SELECT count(*)::text INTO v_s FROM betk.seller_orders WHERE buyer_id = v_expired;
  SELECT count(*)::text INTO v_c FROM betk.cart_items WHERE buyer_id = v_expired;
  PERFORM pg_temp.rec(
    'fail_expired_quote',
    'BETK_CHECKOUT_QUOTE_EXPIRED|0|0|1',
    v_msg || '|' || v_m || '|' || v_s || '|' || v_c
  );

  v_msg := pg_temp.checkout_as(v_band, 'a4000000-0000-4000-8000-00000000000b');
  SELECT count(*)::text INTO v_m FROM betk.master_orders WHERE buyer_id = v_band;
  SELECT count(*)::text INTO v_s FROM betk.seller_orders WHERE buyer_id = v_band;
  SELECT count(*)::text INTO v_c FROM betk.cart_items WHERE buyer_id = v_band;
  PERFORM pg_temp.rec(
    'fail_price_band',
    'BETK_CHECKOUT_QUOTE_OUT_OF_BAND|0|0|1',
    v_msg || '|' || v_m || '|' || v_s || '|' || v_c
  );

  v_msg := pg_temp.checkout_as(v_nophone, 'a4000000-0000-4000-8000-000000000005');
  SELECT count(*)::text INTO v_m FROM betk.master_orders WHERE buyer_id = v_nophone;
  SELECT count(*)::text INTO v_s FROM betk.seller_orders WHERE buyer_id = v_nophone;
  SELECT count(*)::text INTO v_c FROM betk.cart_items WHERE buyer_id = v_nophone;
  v_show := CASE
    WHEN position('row-level security' in v_msg) > 0 THEN 'row-level-security'
    ELSE v_msg
  END;
  PERFORM pg_temp.rec(
    'fail_phone_gate',
    'row-level-security|0|0|1',
    v_show || '|' || v_m || '|' || v_s || '|' || v_c
  );

  -- Happy path. R-O02, R-O17, ADR-022, plan §1.7, §4.2.
  v_msg := pg_temp.checkout_as(v_happy, 'a4000000-0000-4000-8000-000000000001');
  PERFORM pg_temp.rec('happy_ok', 'ok', v_msg);
  SELECT id INTO v_master FROM betk.master_orders WHERE buyer_id = v_happy;

  PERFORM pg_temp.rec(
    'happy_masters',
    '1',
    (SELECT count(*)::text FROM betk.master_orders WHERE buyer_id = v_happy)
  );
  PERFORM pg_temp.rec(
    'happy_seller_orders',
    '2',
    (SELECT count(*)::text FROM betk.seller_orders WHERE buyer_id = v_happy)
  );
  PERFORM pg_temp.rec(
    'happy_shipments',
    '2',
    (
      SELECT count(*)::text
      FROM betk.shipments AS h
      JOIN betk.seller_orders AS s ON s.id = h.order_id
      WHERE s.buyer_id = v_happy
    )
  );
  PERFORM pg_temp.rec(
    'happy_deposit',
    '2|instapay|150.00',
    (
      SELECT count(*)::text
        || '|' || min(p.method)::text
        || '|' || to_char(sum(p.amount), 'FM999990.00')
      FROM betk.payments AS p
      JOIN betk.seller_orders AS s ON s.id = p.order_id
      WHERE s.buyer_id = v_happy AND p.payment_type = 'deposit'
    )
  );
  PERFORM pg_temp.rec(
    'happy_balance',
    '2|cod|150.00',
    (
      SELECT count(*)::text
        || '|' || min(p.method)::text
        || '|' || to_char(sum(p.amount), 'FM999990.00')
      FROM betk.payments AS p
      JOIN betk.seller_orders AS s ON s.id = p.order_id
      WHERE s.buyer_id = v_happy AND p.payment_type = 'balance'
    )
  );
  PERFORM pg_temp.rec(
    'happy_child_allocation',
    '2',
    (
      SELECT count(*)::text
      FROM betk.seller_orders AS s
      JOIN (
        SELECT order_id, sum(amount) AS paid
        FROM betk.payments
        GROUP BY order_id
      ) AS p ON p.order_id = s.id
      WHERE s.buyer_id = v_happy
        AND p.paid = s.total_amount
    )
  );
  PERFORM pg_temp.rec(
    'happy_stock',
    '19|touched|19|touched',
    (
      SELECT
        (SELECT stock_qty::text || '|' || CASE WHEN stock_touched_at IS NOT NULL THEN 'touched' ELSE 'untouched' END
         FROM betk.listings WHERE id = v_list_a)
        || '|' ||
        (SELECT stock_qty::text || '|' || CASE WHEN stock_touched_at IS NOT NULL THEN 'touched' ELSE 'untouched' END
         FROM betk.listings WHERE id = v_list_b)
    )
  );
  PERFORM pg_temp.rec(
    'happy_cart',
    '0',
    (SELECT count(*)::text FROM betk.cart_items WHERE buyer_id = v_happy)
  );
  PERFORM pg_temp.rec(
    'happy_ref',
    'true',
    (
      SELECT (betk_ref ~ '^BETK-[0-9]{8}-[A-F0-9]{4}$')::text
      FROM betk.master_orders
      WHERE id = v_master
    )
  );
  PERFORM pg_temp.rec(
    'happy_child_refs_null',
    '2|2',
    (
      SELECT count(*) FILTER (WHERE betk_ref IS NULL AND display_ref IS NULL)::text
        || '|' || count(*)::text
      FROM betk.seller_orders
      WHERE buyer_id = v_happy
    )
  );
  PERFORM pg_temp.rec(
    'happy_commission',
    '10.00:10.00,10.00:15.00',
    (
      SELECT string_agg(
        to_char(commission_rate, 'FM999990.00') || ':' || to_char(commission_amount, 'FM999990.00'),
        ',' ORDER BY subtotal
      )
      FROM betk.seller_orders
      WHERE buyer_id = v_happy
    )
  );
  PERFORM pg_temp.rec(
    'happy_one_total',
    '300.00|300.00|50.00',
    (
      SELECT to_char(sum(s.subtotal) + m.combined_delivery_total, 'FM999990.00')
        || '|' || to_char(sum(s.total_amount), 'FM999990.00')
        || '|' || to_char(m.combined_delivery_total, 'FM999990.00')
      FROM betk.seller_orders AS s
      JOIN betk.master_orders AS m ON m.id = s.master_order_id
      WHERE s.buyer_id = v_happy
      GROUP BY m.combined_delivery_total
    )
  );
  PERFORM pg_temp.rec(
    'happy_courier',
    '2',
    (
      SELECT count(*)::text
      FROM betk.seller_orders AS s
      JOIN betk.shipments AS h ON h.order_id = s.id
      JOIN betk.courier_rates AS cr ON cr.id = s.courier_rate_id
      WHERE s.buyer_id = v_happy
        AND h.courier = cr.id::text
        AND s.delivery_fee = cr.fee_egp
    )
  );
  PERFORM pg_temp.rec(
    'happy_no_hidden_read',
    'clean',
    CASE
      WHEN position('UPDATE betk.listings' in v_def) > 0 THEN 'updates-listings'
      WHEN position('SELECT delivery_fee' in v_def) > 0 THEN 'selects-delivery-fee'
      WHEN position('SELECT total_amount' in v_def) > 0 THEN 'selects-total'
      WHEN position('RETURNING *' in v_def) > 0 THEN 'returning-star'
      ELSE 'clean'
    END
  );

  -- Seller session. ADR-020, REG-90.
  v_msg := pg_temp.scalar_as(
    v_seller_cairo,
    'authenticated',
    'SELECT delivery_fee::text FROM betk.seller_orders LIMIT 1'
  );
  v_show := CASE
    WHEN position('permission denied' in v_msg) > 0 THEN 'permission-denied'
    ELSE v_msg
  END;
  PERFORM pg_temp.rec('seller_delivery_fee_denied', 'permission-denied', v_show);

  v_msg := pg_temp.scalar_as(
    v_seller_cairo,
    'authenticated',
    'SELECT total_amount::text FROM betk.seller_orders LIMIT 1'
  );
  v_show := CASE
    WHEN position('permission denied' in v_msg) > 0 THEN 'permission-denied'
    ELSE v_msg
  END;
  PERFORM pg_temp.rec('seller_total_amount_denied', 'permission-denied', v_show);

  v_msg := pg_temp.scalar_as(
    v_seller_cairo,
    'authenticated',
    format(
      'SELECT to_char(subtotal, ''FM999990.00'') FROM betk.seller_orders WHERE buyer_id = %L::uuid AND store_id = %L::uuid',
      v_happy,
      v_store_cairo
    )
  );
  PERFORM pg_temp.rec('seller_allowed_subtotal', '100.00', v_msg);

  -- enforce_master_proof_update. Plan §1.7.
  v_msg := pg_temp.exec_as(
    v_happy,
    'authenticated',
    format(
      'UPDATE betk.master_orders SET proof_path = %L, transfer_reference = %L WHERE id = %L::uuid',
      'docs/ci/proof-1.png',
      'CI-REF-1',
      v_master
    )
  );
  SELECT CASE
    WHEN proof_path = 'docs/ci/proof-1.png'
     AND transfer_reference = 'CI-REF-1'
     AND proof_uploaded_at IS NOT NULL
    THEN 'set' ELSE 'unset:' || v_msg
  END INTO v_show
  FROM betk.master_orders
  WHERE id = v_master;
  PERFORM pg_temp.rec('proof_once', 'set', v_show);

  v_msg := pg_temp.exec_as(
    v_happy,
    'authenticated',
    format(
      'UPDATE betk.master_orders SET proof_path = %L WHERE id = %L::uuid',
      'docs/ci/proof-2.png',
      v_master
    )
  );
  PERFORM pg_temp.rec('proof_second', 'BETK_PROOF_ALREADY_SET', v_msg);

  v_msg := pg_temp.checkout_as(v_deadline, 'a4000000-0000-4000-8000-00000000000c');
  IF v_msg <> 'ok' THEN
    RAISE EXCEPTION 'deadline checkout failed: %', v_msg;
  END IF;
  SELECT id INTO v_master FROM betk.master_orders WHERE buyer_id = v_deadline;
  UPDATE betk.master_orders
  SET payment_deadline = now() - interval '1 minute'
  WHERE id = v_master;
  v_msg := pg_temp.exec_as(
    v_deadline,
    'authenticated',
    format(
      'UPDATE betk.master_orders SET proof_path = %L, transfer_reference = %L WHERE id = %L::uuid',
      'docs/ci/late.png',
      'CI-LATE',
      v_master
    )
  );
  PERFORM pg_temp.rec('proof_deadline', 'BETK_PROOF_DEADLINE', v_msg);

  -- release_seller_orders. One admin confirm releases N. Plan §1.7.
  v_msg := pg_temp.checkout_as(v_release, 'a4000000-0000-4000-8000-00000000000d');
  IF v_msg <> 'ok' THEN
    RAISE EXCEPTION 'release checkout failed: %', v_msg;
  END IF;
  SELECT id INTO v_master FROM betk.master_orders WHERE buyer_id = v_release;
  SELECT stock_qty INTO v_before FROM betk.listings WHERE id = v_list_a;
  SELECT p.id INTO v_pay
  FROM betk.payments AS p
  JOIN betk.seller_orders AS s ON s.id = p.order_id
  WHERE s.master_order_id = v_master
    AND p.payment_type = 'deposit'
  ORDER BY s.id
  LIMIT 1;
  v_msg := pg_temp.exec_as(
    v_admin,
    'authenticated',
    format('UPDATE betk.payments SET status = %L WHERE id = %L::uuid', 'confirmed', v_pay)
  );
  IF v_msg <> 'ok' THEN
    RAISE EXCEPTION 'release confirm failed: %', v_msg;
  END IF;
  PERFORM pg_temp.rec(
    'release_confirmed',
    '2|2|2',
    (
      SELECT
        (SELECT count(*)::text FROM betk.seller_orders WHERE master_order_id = v_master AND status = 'confirmed')
        || '|' ||
        (SELECT count(*)::text
         FROM betk.payments AS p
         JOIN betk.seller_orders AS s ON s.id = p.order_id
         WHERE s.master_order_id = v_master
           AND p.payment_type = 'deposit'
           AND p.status = 'confirmed')
        || '|' ||
        (SELECT count(*)::text
         FROM betk.seller_orders
         WHERE master_order_id = v_master AND prep_deadline IS NOT NULL)
    )
  );
  SELECT stock_qty INTO v_after FROM betk.listings WHERE id = v_list_a;
  PERFORM pg_temp.rec('release_stock_once', v_before::text, v_after::text);

  -- restore_stock_on_cancel. Cancel restores. Plan §1.7, REG-82.
  v_msg := pg_temp.checkout_as(v_cancel, 'a4000000-0000-4000-8000-00000000000e');
  IF v_msg <> 'ok' THEN
    RAISE EXCEPTION 'cancel checkout failed: %', v_msg;
  END IF;
  SELECT id INTO v_order FROM betk.seller_orders WHERE buyer_id = v_cancel;
  SELECT stock_qty INTO v_before FROM betk.listings WHERE id = v_list_a;
  v_msg := pg_temp.exec_as(
    v_cancel,
    'authenticated',
    format('UPDATE betk.seller_orders SET status = %L WHERE id = %L::uuid', 'cancelled', v_order)
  );
  IF v_msg <> 'ok' THEN
    RAISE EXCEPTION 'buyer cancel failed: %', v_msg;
  END IF;
  SELECT stock_qty INTO v_after FROM betk.listings WHERE id = v_list_a;
  PERFORM pg_temp.rec('cancel_stock', (v_before + 1)::text, v_after::text);
  PERFORM pg_temp.rec(
    'cancel_cart_and_actor',
    '1|buyer',
    (SELECT count(*)::text FROM betk.cart_items WHERE buyer_id = v_cancel)
      || '|' ||
      (SELECT cancelled_by::text FROM betk.seller_orders WHERE id = v_order)
  );

  -- Expiry: auth.uid() null, deadline past, proof null. cancelled_by system.
  v_msg := pg_temp.checkout_as(v_expiry, 'a4000000-0000-4000-8000-00000000000f');
  IF v_msg <> 'ok' THEN
    RAISE EXCEPTION 'expiry checkout failed: %', v_msg;
  END IF;
  SELECT id INTO v_master FROM betk.master_orders WHERE buyer_id = v_expiry;
  SELECT id INTO v_order FROM betk.seller_orders WHERE buyer_id = v_expiry;
  UPDATE betk.master_orders
  SET payment_deadline = now() - interval '1 minute'
  WHERE id = v_master;
  SELECT stock_qty INTO v_before FROM betk.listings WHERE id = v_list_a;
  PERFORM set_config('request.jwt.claim.sub', '', true);
  PERFORM set_config('request.jwt.claims', '{}', true);
  UPDATE betk.seller_orders SET status = 'cancelled' WHERE id = v_order;
  SELECT stock_qty INTO v_after FROM betk.listings WHERE id = v_list_a;
  PERFORM pg_temp.rec('expiry_stock', (v_before + 1)::text, v_after::text);
  PERFORM pg_temp.rec(
    'expiry_actor',
    'cancelled|system',
    (SELECT status::text || '|' || cancelled_by::text FROM betk.seller_orders WHERE id = v_order)
  );

  -- Return does not restore. ERD §7.1 delivered → returned.
  v_msg := pg_temp.checkout_as(v_return, 'a4000000-0000-4000-8000-000000000010');
  IF v_msg <> 'ok' THEN
    RAISE EXCEPTION 'return checkout failed: %', v_msg;
  END IF;
  SELECT id INTO v_order FROM betk.seller_orders WHERE buyer_id = v_return;
  SELECT stock_qty INTO v_before FROM betk.listings WHERE id = v_list_a;
  SELECT p.id INTO v_pay
  FROM betk.payments AS p
  WHERE p.order_id = v_order AND p.payment_type = 'deposit';
  v_walk := pg_temp.exec_as(
    v_admin, 'authenticated',
    format('UPDATE betk.payments SET status = %L WHERE id = %L::uuid', 'confirmed', v_pay)
  );
  v_walk := v_walk || '|' || pg_temp.exec_as(
    v_seller_cairo, 'authenticated',
    format('UPDATE betk.seller_orders SET status = %L WHERE id = %L::uuid', 'preparing', v_order)
  );
  v_walk := v_walk || '|' || pg_temp.exec_as(
    v_seller_cairo, 'authenticated',
    format('UPDATE betk.seller_orders SET status = %L WHERE id = %L::uuid', 'ready', v_order)
  );
  v_walk := v_walk || '|' || pg_temp.exec_as(
    v_admin, 'authenticated',
    format('UPDATE betk.seller_orders SET status = %L WHERE id = %L::uuid', 'dispatched', v_order)
  );
  v_walk := v_walk || '|' || pg_temp.exec_as(
    v_admin, 'authenticated',
    format('UPDATE betk.seller_orders SET status = %L WHERE id = %L::uuid', 'delivered', v_order)
  );
  BEGIN
    INSERT INTO betk.returns (seller_order_id, buyer_id, store_id, reason, status)
    VALUES (v_order, v_return, v_store_cairo, 'ci', 'accepted');
    v_walk := v_walk || '|ok';
  EXCEPTION WHEN OTHERS THEN
    v_walk := v_walk || '|' || SQLERRM;
  END;
  v_walk := v_walk || '|' || pg_temp.exec_as(
    v_admin, 'authenticated',
    format('UPDATE betk.seller_orders SET status = %L WHERE id = %L::uuid', 'returned', v_order)
  );
  PERFORM pg_temp.rec('return_walk', 'ok|ok|ok|ok|ok|ok|ok', v_walk);
  SELECT stock_qty INTO v_after FROM betk.listings WHERE id = v_list_a;
  PERFORM pg_temp.rec('return_stock', v_before::text, v_after::text);

  -- enforce_order_transition still blocks a seller confirm. ERD §7.1.
  v_msg := pg_temp.checkout_as(v_illegal, 'a4000000-0000-4000-8000-000000000011');
  IF v_msg <> 'ok' THEN
    RAISE EXCEPTION 'illegal checkout failed: %', v_msg;
  END IF;
  SELECT id INTO v_order FROM betk.seller_orders WHERE buyer_id = v_illegal;
  v_msg := pg_temp.exec_as(
    v_seller_cairo, 'authenticated',
    format('UPDATE betk.seller_orders SET status = %L WHERE id = %L::uuid', 'confirmed', v_order)
  );
  PERFORM pg_temp.rec(
    'illegal_transition',
    'BETK_ORDER_RELEASE_ADMIN_ONLY|pending',
    v_msg || '|' || (SELECT status::text FROM betk.seller_orders WHERE id = v_order)
  );

  -- Payout cap. ERD §6.4. Arithmetic only (FLAG-BLOCKING is not filtered).
  INSERT INTO betk.seller_orders (
    betk_ref, buyer_id, store_id, delivery_method, delivery_fee,
    subtotal, total_amount, status, balance_confirmed_at, payout_eligible_at
  ) VALUES (
    'CI-PAYOUT-0001',
    v_payout_buyer,
    v_store_cairo,
    'delivery',
    0,
    200,
    200,
    'pending',
    now() - interval '1 day',
    now() - interval '1 hour'
  );
  v_msg := pg_temp.exec_as(
    v_seller_cairo,
    'authenticated',
    format(
      'INSERT INTO betk.payouts (store_id, amount, method, account_details) VALUES (%L::uuid, 180, %L, %L)',
      v_store_cairo, 'instapay', '01011110002'
    )
  );
  PERFORM pg_temp.rec('payout_within_cap', 'ok', v_msg);
  v_msg := pg_temp.exec_as(
    v_seller_cairo,
    'authenticated',
    format(
      'INSERT INTO betk.payouts (store_id, amount, method, account_details) VALUES (%L::uuid, 100, %L, %L)',
      v_store_cairo, 'instapay', '01011110002'
    )
  );
  PERFORM pg_temp.rec('payout_over_cap', 'BETK_PAYOUT_CAP', v_msg);

  -- enforce_store_category_cap. Limit 3 is the CI pin of seller_category_limit.
  SELECT id INTO v_c1 FROM betk.categories WHERE is_active ORDER BY slug OFFSET 0 LIMIT 1;
  SELECT id INTO v_c2 FROM betk.categories WHERE is_active ORDER BY slug OFFSET 1 LIMIT 1;
  SELECT id INTO v_c3 FROM betk.categories WHERE is_active ORDER BY slug OFFSET 2 LIMIT 1;
  SELECT id INTO v_c4 FROM betk.categories WHERE is_active ORDER BY slug OFFSET 3 LIMIT 1;
  IF v_c4 IS NULL THEN
    RAISE EXCEPTION 'BETK_CI_NEED_CATEGORIES';
  END IF;
  v_walk := pg_temp.exec_as(
    v_seller_cairo, 'authenticated',
    format('INSERT INTO betk.store_categories (store_id, category_id) VALUES (%L::uuid, %L::uuid)', v_store_cairo, v_c1)
  );
  v_walk := v_walk || '|' || pg_temp.exec_as(
    v_seller_cairo, 'authenticated',
    format('INSERT INTO betk.store_categories (store_id, category_id) VALUES (%L::uuid, %L::uuid)', v_store_cairo, v_c2)
  );
  v_walk := v_walk || '|' || pg_temp.exec_as(
    v_seller_cairo, 'authenticated',
    format('INSERT INTO betk.store_categories (store_id, category_id) VALUES (%L::uuid, %L::uuid)', v_store_cairo, v_c3)
  );
  v_walk := v_walk || '|' || pg_temp.exec_as(
    v_seller_cairo, 'authenticated',
    format('INSERT INTO betk.store_categories (store_id, category_id) VALUES (%L::uuid, %L::uuid)', v_store_cairo, v_c4)
  );
  v_walk := v_walk || '|' || (
    SELECT count(*)::text FROM betk.store_categories WHERE store_id = v_store_cairo
  );
  PERFORM pg_temp.rec(
    'category_cap',
    'ok|ok|ok|BETK_STORE_CATEGORY_CAP|3',
    v_walk
  );

  -- Anon cannot call checkout. Plan §6 M7.
  v_msg := pg_temp.exec_as(
    NULL,
    'anon',
    'DO $anon$ BEGIN PERFORM betk.checkout_from_cart(NULL::uuid); END $anon$'
  );
  v_show := CASE
    WHEN position('permission denied' in v_msg) > 0 THEN 'permission-denied'
    ELSE v_msg
  END;
  PERFORM pg_temp.rec('anon_checkout_denied', 'permission-denied', v_show);
END;
$cases$;

INSERT INTO m78_results (name, expected, actual, pass)
SELECT
  'all_pass',
  'true|58',
  bool_and(pass)::text || '|' || count(*)::text,
  bool_and(pass) AND count(*) = 58
FROM m78_results;

SELECT name, expected, actual, pass
FROM m78_results
ORDER BY ord;

COMMIT;
